[package]
name = "ddfloppy"
description = "Visualizes ddrescue progress for floppies"
version = "0.1.0"
authors = ["Matti Virkkunen <mvirkkunen@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.13"
druid = "0.6.0"
